#! /bin/sh

case "$1" in
	start|"")
		echo -n "Starting miscellaneous setup: "
		# Restore saved password and Dropbear keys
		[[ -d /mnt/jffs2/etc ]] && cd /mnt/jffs2/etc && md5sum -s -c password.md5 && cp passwd shadow group /etc
		[[ -d /mnt/jffs2/etc/dropbear ]] && cd /mnt/jffs2/etc/dropbear && md5sum -s -c keys.md5 && cp dropbear* /etc/dropbear/
		[[ -d /mnt/jffs2/root/.ssh ]] && cd /mnt/jffs2/root/.ssh && md5sum -s -c keys.md5 && mkdir /root/.ssh && cp authorized_keys /root/.ssh

		# Mount configfs
		mount configfs -t configfs /sys/kernel/config 2> /dev/null
		
		MAX_BS=`fw_printenv -n iio_max_block_size 2> /dev/null || echo 67108864`
		echo ${MAX_BS} > /sys/module/industrialio_buffer_dma/parameters/max_block_size
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)

		;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac
